# Generated by Django 3.2 on 2022-07-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(default='m', max_length=2)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=100)),
                ('web', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField()),
                ('response', models.TextField(blank=True, default='')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
