# Generated by Django 3.2 on 2022-07-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardunit',
            old_name='content',
            new_name='bcontent',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='gender',
            new_name='bgender',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='email',
            new_name='bmail',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='name',
            new_name='bname',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='response',
            new_name='bresponse',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='subject',
            new_name='bsubject',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='datetime',
            new_name='btime',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='web',
            new_name='bweb',
        ),
    ]
