# Generated by Django 3.2 on 2022-07-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0002_auto_20220721_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardunit',
            old_name='bmail',
            new_name='base_bmail',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='bcontent',
            new_name='base_content',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='bgender',
            new_name='base_gender',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='bname',
            new_name='base_name',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='bresponse',
            new_name='base_response',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='bsubject',
            new_name='base_subject',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='btime',
            new_name='base_time',
        ),
        migrations.RenameField(
            model_name='boardunit',
            old_name='bweb',
            new_name='base_web',
        ),
    ]
