# Generated by Django 3.2 on 2022-07-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0003_auto_20220721_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardUnit',
            new_name='Board',
        ),
    ]
